# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend-env
# data:
#   .env: |
#     REACT_APP_BACKEND_URL=http://backend-service

# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: frontend-env  # Define the volume with the correct name
          configMap:
            name: frontend-env  # Reference the ConfigMap name
      containers:
        - name: frontend
          image: public.ecr.aws/o8s7i5y4/zocket-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: frontend-env
              mountPath: /usr/share/nginx/html/.env
              subPath: .env
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://172.20.206.80:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
