name: Deploy Image to EKS

on:
  push:
    branches:
      - eks
  pull_request:
    branches:
      - eks

env:
  AWS_REGION: ap-south-1
  ECR_REPO: zocket-frontend
  IMAGE_NAME: zocket-frontend
  AWS_ACCOUNT_ID: "891377385230"

jobs:
  update-kubectl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CLI and kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli 
          
      - name: Install eksctl
        run: |
          sudo wget https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz
          sudo tar -xvf eksctl_$(uname -s)_amd64.tar.gz
          sudo mv eksctl /usr/local/bin
          eksctl version
    
      - name: Install kubectl
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y kubectl
          
      - name: Configure kubectl
        run: aws eks update-kubeconfig --name zocket-cluster --region ap-south-1

      - name: Deploy Kubernetes Application
        run: |
              kubectl get svc
              kubectl get pods
              # kubectl delete svc frontend --force
              kubectl exec frontend-deployment-77ddc4bd9b-ntwph -- sh -c "curl http://backend-service/api/tasks"
              # kubectl exec frontend-deployment-77ddc4bd9b-ntwph -- sh -c "printenv | grep REACT_APP_BACKEND_URL"
              kubectl logs frontend-deployment-77ddc4bd9b-ntwph --tail=20
              # kubectl replace -f kubernetes/manifests/frontend.yml --force

      - name: Get Service Endpoint
        run: |
               kubectl get pods
               kubectl get svc
